services:
  app:
    build: .
    ports:
      - "6565:6565"
      - "8080:8080"
    environment:
      - AB_CLIENT_ID=${AB_CLIENT_ID}
      - AB_CLIENT_SECRET=${AB_CLIENT_SECRET}
      - AB_BASE_URL=${AB_BASE_URL}
      - AB_NAMESPACE=${AB_NAMESPACE}
      - EOS_VOICE_DEPLOYMENT_ID=${EOS_VOICE_DEPLOYMENT_ID}
      - EOS_VOICE_CLIENT_ID=${EOS_VOICE_CLIENT_ID}
      - EOS_VOICE_CLIENT_SECRET=${EOS_VOICE_CLIENT_SECRET}
      - EOS_VOICE_NOTIFICATION_TOPIC=${EOS_VOICE_NOTIFICATION_TOPIC:-EOS_VOICE}
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://host.docker.internal:9411/api/v2/spans # Zipkin
      - OTEL_SERVICE_NAME=ExtendEOSVoiceRTC
      # - GRPC_GO_LOG_VERBOSITY_LEVEL="99" # enable to debug grpc
      # - GRPC_GO_LOG_SEVERITY_LEVEL=info # enable to debug grpc
    extra_hosts:
      - host.docker.internal:host-gateway
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: http://host.docker.internal:3100/loki/api/v1/push
    #     mode: non-blocking
    #     max-buffer-size: 4m
    #     loki-retries: "3"
